debug 2

diff --git a/.github/workflows/reusable-build-macos-desktop.yml b/.github/workflows/reusable-build-macos-desktop.yml
--- a/.github/workflows/reusable-build-macos-desktop.yml
+++ b/.github/workflows/reusable-build-macos-desktop.yml
@@ -42,6 +42,12 @@ jobs:
             else
               echo "✅ SUCCESS: GitHub Secrets are loaded!"
             fi
+            if [ -z "${{ secrets.CSC_KEY_PASSWORD }}" ]; then
+              echo "❌ ERROR: CSC_KEY_PASSWORD are EMPTY! The workflow cannot see them."
+              exit 1
+            else
+              echo "✅ SUCCESS: CSC_KEY_PASSWORD is loaded, length is ${#CSC_KEY_PASSWORD} characters!"
+            fi
             pnpm electron:package:mac
 
       - name: Rename DMG for release
